### ISSUE TITLE
Remove foo.es6.js from build routines and element repos

### ISSUE THREAD

**Issue by ilovemilk** [elmsln/lrnwebcomponents#271] opened 2019-06-05 11:37 UTC
Hi
I get the following error when packing my frontend bundle with webpack:

```
ERROR in ./node_modules/@lrnwebcomponents/paper-stepper/paper-stepper.es6.js
    Module not found: Error: Can't resolve './node_modules/@polymer/polymer/polymer-legacy.js' in 'C:\Projects\project\frontend-components\src\main\js\node_modules\@lrnwebcomponents\paper-stepper'
     @ ./node_modules/@lrnwebcomponents/paper-stepper/paper-stepper.es6.js 1:0-82 2:19-26
     @ ./src/index.js
```

It seems that the import of `polymer-legacy.js` in your paper-stepper bundle is wrong.

Best regards
Matthias

**Comment by btopro** [comment] 2019-06-05 15:42
hmm it's not that way in the source in this repohttps://github.com/elmsln/lrnwebcomponents/blob/master/elements/paper-stepper/paper-stepper.es6.js

Do you get the same issue pointing to paper-stepper.js? We don't use webpack so the additional compiled versions aren't tested (which would explain the path being off potentially).

I'll publish new versions to npm as they have been updated to get rid of polymer-legacy at minimum

**Comment by ilovemilk** [comment] 2019-06-06 08:05
Hi btopro

Thanks that would be awesome!
If I use `paper-stepper.js` I get no errors, but with webpack and es6 this pops up.

Best regards
Matthias

**Comment by btopro** [comment] 2019-06-06 14:48
so are you good then if you just directly reference the main file and then pull that in or is webpack still sniffing out this es6 "variant" (which it really isn't at this point)? I can always remove the .es6. versions if they don't actually work. I was under the impression resolving them via build and keeping them in the repo would help w/ those still doing bundling but as I don't bundle it was a guess and pray scenario.

**Comment by ilovemilk** [comment] 2019-06-07 12:23
Yes I am fine with pulling this file directly but I would recommend removing the es6 version because it simply doesn't work to make sure another user doesn't have the same issues.

Thanks for your fast help!

**Comment by btopro** [comment] 2019-06-07 12:25
works for me, it'll speed up my build routines on publishing. I'll rename this issue and look into that more holistically.

**Comment by btopro** [comment] 2019-07-15 12:44
@heyMP as we were talking about this last night and you seemed a bit more knowledgable on the subject RE Pika Package, could you see what needs done w/ an element to get it up to snuff for this? I'm fine with simplifying our packaging routine if the umd / amd / es5 versions of the project don't do anything meaningful. Would speed up build / publish routine a lot when I go to do it across the portfolio.

**Comment by btopro** [comment] 2019-08-03 04:05
this should be cleaned up in all of our elements now with new versions currently publishing to npm. Hopefully this means we'll be able to use them on pika.dev but will have to wait till they all go up to see

**Closed by btopro** 2019-08-03 04:05 UTC

**Comment by btopro** [comment] 2019-08-03 04:38
I can confirm these show up in pika.dev meaning they should be good now
